# Use an official Node.js runtime as a parent image
FROM node:20

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Generate Prisma Client
RUN npx prisma generate

# Expose the port your application will listen on
EXPOSE 3002

# Define the command to run your application
CMD [ "sh", "-c", "npx prisma migrate deploy && npm start" ]
